gl_detail_and_queries
fylein/sageintacct-sdk-py pull request #25
Opened 2021-08-28 22:19 UTC by CPAanalytics

2021-08-28 22:21 UTC, CPAanalytics commented
Added the gl_detail class.
Added ability to create advanced queries using get_by_query().
Updated Readme.

2021-08-30 06:05 UTC, Shwetabhk approved these changes

2021-08-30 06:11 UTC, ashwin1111 requested changes
@CPAanalytics couple of super minor comments, please fix it off and then we're good to merge and release.

2021-08-30 06:11 UTC, ashwin1111 commented on sageintacctsdk/apis/api_base.py
> +        print(data)
Please remove this print statement

2021-08-30 06:11 UTC, ashwin1111 commented on sageintacctsdk/apis/gl_detail.py
> +    """Class for AP Payments APIs."""
"""Class for GL Detail APIs."""

2021-08-30 12:03 UTC, CPAanalytics commented
Made these corrections.  Thanks for the opportunity to contribute.  I expect to use this SDK quite a bit so I may have some more pull requests.

2021-08-30 13:04 UTC, Shwetabhk approved these changes

2021-08-30 13:05 UTC, merged

2021-08-30 13:10 UTC, Shwetabhk commented
https://github.com/fylein/sageintacct-sdk-py/releases/tag/1.6.0
@CPAanalytics this has been released in version `1.6.0`
https://pypi.org/project/sageintacctsdk/